apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-spring-boot-app
spec:
  schedule: "* * * * *" #	Run every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: my-spring-boot-app
              image: codewithsri/my-springboot-app:1.0.0
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - date; echo Hello!
          restartPolicy: OnFailure